import Head from 'next/head'
import Hero from "../components/Hero/Hero";

export default function Home() {
  return (
      <div>
        <Head>
          <title>This is the home page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <h1>Home</h1>
      </div>
  )
}
